name: rmusd
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pytorch=2.2.0
  - torchvision=0.17.0
  - torchaudio=2.2.0
  - pytorch-cuda=11.8 
  - timm=1.0.8
  - numpy=1.26.4
  - accelerate=1.4.0
  - albumentations=1.4.14
  - huggingface_hub=0.29.1
  - opencv=4.10.0
  - pillow=10.3.0
  - libstdcxx-ng=13.2.0
  - libgcc-ng=13.2.0
  - pandas=2.2.2
  - scikit-learn=1.4.0
  - scipy=1.11.1
  - pip=24.2
  - pip:
      - diffusers==0.29.0
      - transformers==4.38.0
      - datasets==2.17.0
      - accelerate==0.32.1
      - matplotlib==3.9.0
      - nudenet==3.4.0
      - clean-fid==0.1.35
      - open-clip-torch==2.24.0
      - openai-clip==1.0.1
